### ISSUE TITLE
Integrate one-click launch of a database

### ISSUE THREAD

**Issue by koppor** [ultimate-comparisons/ultimate-TSDB-comparison#1]
We have installation scripts for databases available at https://github.com/TSDBBench/TSDBBench/tree/master/databases. With the help of vagrant, it should be possible to enable users to install a database on [DigitalOcean](https://www.digitalocean.com/) or similar cloud providers.

**Comment by baderas** [comment]
The main problem is: How to provide a linux base image, but that should be possible (like it is already possible for vSphere).
The remaining part is a appropriate vagrant plugin, something like https://github.com/smdahlen/vagrant-digitalocean seems to exist and should work ;)

**Comment by koppor** [comment]
I can host a linux-based image on my server. There should be a script for building that image and the users should be able to change the URL for the image. That makes the process transparent and they can be sure, not backdoors are in place. :smiley:
